name: Monitor de Privacidad (Candado)

on:
  schedule:
    - cron: "*/30 * * * *" # Cada 30 min
  workflow_dispatch:

permissions:
  contents: write

jobs:
  vigilancia:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install requests beautifulsoup4

      - name: Ejecutar el Bot Espía
        # --- AQUÍ CONECTAMOS LOS SECRETOS ---
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          LISTA_OBJETIVOS: ${{ secrets.LISTA_OBJETIVOS }}
        # ------------------------------------
        run: python bot_candado_siempre.py

      - name: Guardar base de datos
        run: |
          git config --global user.name "Bot de Vigilancia"
          git config --global user.email "bot@github.com"
          git add estado_privacidad.json
          git commit -m "Actualizar estado de privacidad" || exit 0
          git push
